# file: postgresql/tasks/configure.yml

- name: PostgreSQL | Reset the cluster - drop the existing one
  shell: pg_dropcluster --stop {{postgresql_version}} {{postgresql_cluster_name}}
  sudo: yes
  sudo_user: postgresql
  when: postgresql_cluster_reset

- name: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale)
  shell: pg_createcluster --start --locale {{postgresql_locale}} -e {{postgresql_encoding}} {{postgresql_version}} {{postgresql_cluster_name}}
  sudo: yes
  sudo_user: postgresql
  when: postgresql_cluster_reset

- name: PostgreSQL | Update configuration - pt. 1 (pg_hba.conf)
  template:
    src: etc_postgresql_version_cluster_pg_hba.conf.j2
    dest: "/etc/postgresql/{{postgresql_version}}/{{postgresql_cluster_name}}/pg_hba.conf"
    owner: "{{postgresql_admin_user}}"
    group: "{{postgresql_admin_user}}"
    mode: 0640
  notify:
    - restart postgresql
